services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5556:5556"
    volumes:
      - data:/var/lib/postgresql/data
    container_name: POSTGRES_DB

volumes:
  data:
